# Copyright © 2026 The Blue View Group Corporation and Frank Perez (frank@blueview.ai).
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
# Maximum PipeWire resampler precision when source and graph rates differ.
# Preserve negotiated rates, channel maps, volumes, and the 48 kHz hardware path.
stream.properties = {
    resample.quality = 14
}
