# Copyright © 2026 The Blue View Group Corporation and Frank Perez (frank@blueview.ai).
# Adapted from PipeWire's sink-upmix-5.1-filter.conf (Copyright © 2018 Wim Taymans).
# See third-party/PIPEWIRE-COPYING for PipeWire's MIT notice.
context.modules = [
  { name = libpipewire-module-filter-chain
    flags = [ nofail ]
    args = {
      node.description = "Blue View Open Quad Spatial"
      media.name = "Blue View Open Quad Spatial"
      filter.graph = {
        nodes = [
          { type = builtin label = copy name = copyFL }
          { type = builtin label = copy name = copyFR }
          { type = builtin label = copy name = copyOFL }
          { type = builtin label = copy name = copyOFR }
          { type = builtin label = mixer name = subR control = { "Gain 1" = 0.707 "Gain 2" = -0.707 } }
          { type = builtin label = convolver name = convRL config = { gain = 1.0 delay = 0.012 filename = "/hilbert" length = 33 latency = 0.0 } }
          { type = builtin label = convolver name = convRR config = { gain = -1.0 delay = 0.012 filename = "/hilbert" length = 33 latency = 0.0 } }
        ]
        links = [
          { output = "copyFL:Out" input = "subR:In 1" }
          { output = "copyFR:Out" input = "subR:In 2" }
          { output = "copyFL:Out" input = "copyOFL:In" }
          { output = "copyFR:Out" input = "copyOFR:In" }
          { output = "subR:Out" input = "convRL:In" }
          { output = "subR:Out" input = "convRR:In" }
        ]
        inputs = [ "copyFL:In" "copyFR:In" ]
        outputs = [ "copyOFL:Out" "copyOFR:Out" "convRL:Out" "convRR:Out" ]
      }
      capture.props = {
        node.name = "effect_input.blue_view_open_quad"
        media.class = Audio/Sink
        audio.channels = 2
        audio.position = [ FL FR ]
      }
      playback.props = {
        node.name = "effect_output.blue_view_open_quad"
        node.passive = true
        target.object = "imac_fixed"
        audio.channels = 4
        audio.position = [ FL FR RL RR ]
      }
    }
  }
]
